lib/elixir_kids_web/router.ex
defmodule ElixirKidsWeb.Router do
  use ElixirKidsWeb, :router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :live_layouts do
    plug :put_root_layout, {ElixirKidsWeb.LayoutView, :live }
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ElixirKidsWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/categories", CategoryController
    resources "/posts", PostController
    resources "/medias", MediaController
    resources "/neighborhoods", NeighborhoodController
  end

  scope "/live", ElixirKidsWeb do
    pipe_through [:browser, :live_layouts]

    live "/neighborhoods/new", NeighborhoodLive.New
    live "/neighborhoods/:id", NeighborhoodLive.Show
    live "/neighborhoods/:id/edit", NeighborhoodLive.Edit
    live "/neighborhoods", NeighborhoodLive.Index
  end

  # Other scopes may use custom stacks.
  # scope "/api", ElixirKidsWeb do
  #   pipe_through :api
  # end
end

lib/elixir_kids/blog/neighborhood.ex
defmodule ElixirKids.Blog.Neighborhood do
  use Ecto.Schema
  import Ecto.Changeset

  alias GoogleMaps, as: Maps

  schema "neighborhoods" do
    field :latitude, :float
    field :longitude, :float
    field :name, :string

    timestamps()
  end

  @doc false
  def changeset(neighborhood, attrs) do
    neighborhood
    |> cast(attrs, [:name, :latitude, :longitude])
    |> validate_required([:name])
    |> get_coordinates
  end

  defp get_coordinates(changeset) do
    name = changeset.data.name
    { :ok, result } = Maps.geocode("#{name}, Oslo")
    coordinates = Enum.map(result["results"], fn (x) -> x["geometry"]["location"] end)
    %{ "lat" => lat, "lng" => lng } = Enum.at(coordinates, 0)
    changeset |> put_change(:latitude, lat) |> put_change(:longitude, lng)
  end
end

lib/elixir_kids_web/controllers/neighborhood_controller.ex
defmodule ElixirKidsWeb.NeighborhoodController do
  use ElixirKidsWeb, :controller

  alias ElixirKids.Blog
  alias ElixirKids.Blog.Neighborhood
  alias ElixirKids.PubSub

  def index(conn, _params) do
    neighborhoods = Blog.list_neighborhoods()
    render(conn, "index.html", neighborhoods: neighborhoods)
  end

  def new(conn, _params) do
    changeset = Blog.change_neighborhood(%Neighborhood{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"neighborhood" => neighborhood_params}) do

    case Blog.create_neighborhood(neighborhood_params) do
      {:ok, neighborhood} ->
        conn
        |> put_flash(:info, "Neighborhood created successfully.")
        |> redirect(to: Routes.neighborhood_path(conn, :show, neighborhood))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    neighborhood = Blog.get_neighborhood!(id)
    render(conn, "show.html", neighborhood: neighborhood)
  end

  def edit(conn, %{"id" => id}) do
    neighborhood = Blog.get_neighborhood!(id)
    changeset = Blog.change_neighborhood(neighborhood)
    render(conn, "edit.html", neighborhood: neighborhood, changeset: changeset)
  end

  def update(conn, %{"id" => id, "neighborhood" => neighborhood_params}) do
    neighborhood = Blog.get_neighborhood!(id)

    case Blog.update_neighborhood(neighborhood, neighborhood_params) do
      {:ok, neighborhood} ->
        conn
        |> put_flash(:info, "Neighborhood updated successfully.")
        |> redirect(to: Routes.neighborhood_path(conn, :show, neighborhood))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", neighborhood: neighborhood, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    neighborhood = Blog.get_neighborhood!(id)
    {:ok, _neighborhood} = Blog.delete_neighborhood(neighborhood)

    conn
    |> put_flash(:info, "Neighborhood deleted successfully.")
    |> redirect(to: Routes.neighborhood_path(conn, :index))
  end
end

lib/elixir_kids_web/views/neighborhood_view.ex
defmodule ElixirKidsWeb.NeighborhoodView do
  use ElixirKidsWeb, :view

  alias ElixirKidsWeb.NeighborhoodLive
end

lib/elixir_kids_web/templates/neighborhood/edit.html.leex
<a href="<%= Routes.live_path(@socket, ElixirKidsWeb.NeighborhoodLive.Index) %>" class="button is-link is-pulled-right" >
  <span class="icon is-small">
      <i class="fas fa-arrow-left"></i>
  </span>
  <span>Back</span>
</a>

<h1 class="is-size-3">
    Edit Neighborhood
</h1>

<%= render "form.html", assigns %>

lib/elixir_kids_web/templates/neighborhood/form.html.leex
<%= f = form_for @changeset, "#", [phx_change: :validate, phx_submit: :save ] %>
  <div class="field">
    <label class="label"><%= label f, :name %></label>
    <%= text_input f, :name, class: "input"  %>
    <p class="help is-danger">
      <%= error_tag f, :name %>
    </p>
  </div>


  <div class="field">
    <div class="control">
      <%= submit "Save", phx_disable_with: "Saving...", class: "button is-success is-pulled-right"  %>
    </div>
  </div>
</form>

lib/elixir_kids_web/templates/neighborhood/index.html.leex
<span>
  <%= link "Add Neighborhood", 
    to: Routes.live_path(@socket, ElixirKidsWeb.NeighborhoodLive.New),
    class: "button is-primary is-outlined is-pulled-right" 
  %>
</span>
<h1 class="is-size-3">Neighborhoods</h1>
  
<table class="table is-striped is-fullwidth" phx-keydown-window="keydown" phx-throttle="500">
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= for neighborhood <- @neighborhoods do %>
      <tr>
        <td><%= neighborhood.name %></td>
        <td><%= neighborhood.latitude %></td>
        <td><%= neighborhood.longitude %></td>

        <td>
          <div class="is-pulled-right">
            <span>
              <%= link "Show", 
                to: Routes.live_path(@socket, ElixirKidsWeb.NeighborhoodLive.Show, neighborhood.id, []),
                class: "button is-info is-small is-outlined" 
              %>
            </span>
            <span>          
              <%= link "Edit", 
                to: Routes.live_path(@socket, ElixirKidsWeb.NeighborhoodLive.Edit, neighborhood.id, []),
                class: "button is-warning is-small " 
              %>
            </span>
            <span>
              <%= link "Delete", to: "#",
                phx_click: "delete_neighborhood",
                phx_value_id: neighborhood.id,
                data: [confirm: "Are you sure?"], 
                class: "button is-danger is-small is-outlined"
              %>
            </span>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= if @page > 1 do %>
  <span><%= live_patch "prev", to: Routes.live_path(@socket,  ElixirKidsWeb.NeighborhoodLive.Index, page: @page - 1) %></span>
<% end %>
<span><%= live_patch "next", to: Routes.live_path(@socket, ElixirKidsWeb.NeighborhoodLive.Index, page: @page + 1) %></span>
<br/>

lib/elixir_kids_web/templates/neighborhood/new.html.leex
<a href="<%= Routes.live_path(@socket, ElixirKidsWeb.NeighborhoodLive.Index) %>" class="button is-link is-pulled-right" >
  <span class="icon is-small">
      <i class="fas fa-arrow-left"></i>
  </span>
  <span>Back</span>
</a>
<h1 class="is-size-3">
    New Neighborhood
</h1>

<%= render "form.html", assigns %>

lib/elixir_kids_web/templates/neighborhood/show.html.leex
<a href="<%= Routes.live_path(@socket, ElixirKidsWeb.NeighborhoodLive.Index) %>" class="button is-link is-pulled-right" >
  <span class="icon is-small">
      <i class="fas fa-arrow-left"></i>
  </span>
  <span>Back</span>
</a>
<div class="box">
  <h1 class="is-size-3">
    Neighborhood #<%= @neighborhood.id %>
  </h1>
  <ul>
    <li>
      <strong>Name:</strong>
      <%= @neighborhood.name %>
    </li>

    <li>
      <strong>Latitude:</strong>
      <%= @neighborhood.latitude %>
    </li>

    <li>
      <strong>Longitude:</strong>
      <%= @neighborhood.longitude %>
    </li>

  </ul>
</div>